version: '2.2'

x-server-common:
  &server-common
  network_mode: host
  build: 
    context: ./video-server
  volumes:
    - ./sessions:/opt/mqtt-server/data
    - ./video-server/server:/opt/mqtt-server/server
    - ./video-server/scripts:/opt/mqtt-server/scripts
    - ./video-server/libs:/opt/mqtt-server/libs

services:
  emotions-dashboard:
    network_mode: host
    build: 
      context: ./simple-interface
    environment:
      HOST: "${HOST}"
    #   POSTGRES_USER: airflow
    #   POSTGRES_PASSWORD: airflow
    #   POSTGRES_DB: airflow
    volumes:
      - ./simple-interface/server:/opt/emotions-dashboard/server
      - ./simple-interface/frontend:/opt/emotions-dashboard/frontend
      - ./sessions:/opt/emotions-dashboard/sessions
    stdin_open: true

  mqtt-broker:
    network_mode: host
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  mqtt-server:
    <<: *server-common
    command: bash -c "cd ./server && python ./server.py"
    restart: always
    depends_on:
      - mqtt-broker

  assembler:
    <<: *server-common
    environment:
      MNE_USE_NUMBA: 'false'
    command: bash -c "cd ./scripts && python ./assembler.py && sleep 10"
    restart: always    

  static-server:
    network_mode: host
    image: halverneus/static-file-server:latest
    volumes:
      - ./sessions:/web 
